// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUl5YsrgRLZn7nqnvKstwB6-PwsKOu3D8',
    appId: '1:491479929136:web:26b60b689f5cdd27bcf8f5',
    messagingSenderId: '491479929136',
    projectId: 'shopsbank-405b5',
    authDomain: 'shopsbank-405b5.firebaseapp.com',
    databaseURL: 'https://shopsbank-405b5-default-rtdb.firebaseio.com',
    storageBucket: 'shopsbank-405b5.appspot.com',
    measurementId: 'G-RV23130VN4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUl5YsrgRLZn7nqnvKstwB6-PwsKOu3D8',
    appId: '1:491479929136:web:26b60b689f5cdd27bcf8f5',
    messagingSenderId: '491479929136',
    projectId: 'shopsbank-405b5',
    authDomain: 'shopsbank-405b5.firebaseapp.com',
    storageBucket: 'shopsbank-405b5.appspot.com',
    measurementId: 'G-RV23130VN4',
  );
}